steps:
  # 1️⃣ Maven으로 프로젝트 빌드 (JAR 파일 생성)
  - name: 'maven:3.8.5'
    entrypoint: 'mvn'
    args: ['clean', 'package']

  # 2️⃣ Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cicd-test', '.']

  # 3️⃣ Docker 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cicd-test']
